"""Initial schema — companies, users, memberships, scheduling, swaps, API licensing.

Revision ID: 0001
Revises:
Create Date: 2026-06-08

Hand-written (not autogenerated, since this stands up the schema from scratch to
mirror the current Firestore document structure). Mirrors the schema sketched
during the FastAPI/Postgres migration planning.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Enum types are created explicitly (create_type=False on the columns) so that
# referencing the same enum from multiple tables doesn't attempt CREATE TYPE twice.
membership_role = postgresql.ENUM("user", "admin", name="membership_role", create_type=False)
invitation_status = postgresql.ENUM(
    "pending", "accepted", "expired", "revoked", name="invitation_status", create_type=False
)
month_status = postgresql.ENUM(
    "draft", "open", "closed", "scheduled", "archived", name="month_status", create_type=False
)
shift_type = postgresql.ENUM("night", "day", name="shift_type", create_type=False)
swap_status = postgresql.ENUM("pending", "accepted", "declined", "cancelled", name="swap_status", create_type=False)

ENUM_TYPES = (membership_role, invitation_status, month_status, shift_type, swap_status)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ENUM_TYPES:
        enum_type.create(bind, checkfirst=True)

    op.create_table(
        "companies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("firebase_uid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("firebase_uid", name="uq_users_firebase_uid"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_firebase_uid", "users", ["firebase_uid"])
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "memberships",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("role", membership_role, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("max_shifts", sa.Integer(), nullable=True),
        sa.Column(
            "preferred_coworker_ids",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
            server_default="{}",
        ),
        sa.UniqueConstraint("user_id", "company_id", name="uq_membership_user_company"),
    )

    op.create_table(
        "invitations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", membership_role, nullable=False),
        sa.Column("status", invitation_status, nullable=False, server_default="pending"),
        sa.Column("invited_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_invitations_email", "invitations", ["email"])

    op.create_table(
        "calendar_months",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("month_id", sa.String(), nullable=False),
        sa.Column("org_name", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("intake_limit_per_shift", sa.Integer(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", month_status, nullable=False, server_default="draft"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("company_id", "month_id", name="uq_calendar_month_company_month"),
    )

    op.create_table(
        "availabilities",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "calendar_month_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("calendar_months.id"), nullable=False
        ),
        sa.Column("member_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("calendar_month_id", "member_id", name="uq_availability_month_member"),
    )

    op.create_table(
        "availability_entries",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column(
            "availability_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("availabilities.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("shift_type", shift_type, nullable=False),
    )
    op.create_index("ix_availability_entries_availability_id", "availability_entries", ["availability_id"])

    op.create_table(
        "assignments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "calendar_month_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("calendar_months.id"), nullable=False
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("weekday_label", sa.String(), nullable=False),
        sa.Column("weekend", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("night_slot_0", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("night_slot_1", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("day_slot_0", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("day_slot_1", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.UniqueConstraint("calendar_month_id", "date", name="uq_assignment_month_date"),
    )

    op.create_table(
        "swap_requests",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "calendar_month_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("calendar_months.id"), nullable=False
        ),
        sa.Column("status", swap_status, nullable=False, server_default="pending"),
        sa.Column("requester_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("requestee_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("requester_date", sa.Date(), nullable=False),
        sa.Column("requester_shift_type", shift_type, nullable=False),
        sa.Column("requester_slot", sa.SmallInteger(), nullable=False),
        sa.Column("requestee_date", sa.Date(), nullable=False),
        sa.Column("requestee_shift_type", shift_type, nullable=False),
        sa.Column("requestee_slot", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "api_keys",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("client_name", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False, server_default="60"),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("key_hash", name="uq_api_keys_key_hash"),
    )
    op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"])

    op.create_table(
        "api_usage_events",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("api_key_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("api_keys.id"), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("status_code", sa.SmallInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_api_usage_events_api_key_id", "api_usage_events", ["api_key_id"])


def downgrade() -> None:
    op.drop_table("api_usage_events")
    op.drop_table("api_keys")
    op.drop_table("swap_requests")
    op.drop_table("assignments")
    op.drop_table("availability_entries")
    op.drop_table("availabilities")
    op.drop_table("calendar_months")
    op.drop_table("invitations")
    op.drop_table("memberships")
    op.drop_table("users")
    op.drop_table("companies")

    bind = op.get_bind()
    for enum_type in reversed(ENUM_TYPES):
        enum_type.drop(bind, checkfirst=True)
